version: "3"

services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    networks:
      - mynetwork
  db-test:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3307:3306"
    networks:
      - mynetwork
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-delivery-application
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    volumes:
      - ./src:/app/src
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge